CREATE TABLE IF NOT EXISTS Food
(
	FoodID INT NOT NULL PRIMARY KEY,
	Category VARCHAR(40) NOT NULL,
	VegMenu BOOL NULL,
	ChildrenMenu BOOL NULL,
	Bar BOOL NULL,
	Cost INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Tour
(
	TourID INT NOT NULL PRIMARY KEY,
	Food INT NOT NULL,
	Hotel INT NOT NULL,
	Transfer INT NOT NULL,
	Cost INT NOT NULL,
	DateBegin DATE NOT NULL,
	DateEnd DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS Hotel
(
	HotelID INT NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Type VARCHAR(30) NULL,
	Class INT NULL,
	SwimPool BOOL NULL,
	City VARCHAR(30) NULL,
	Cost INT NOT NULL
);

CREATE TABLE IF NOT EXISTS Users
(
	UserID INT NOT NULL PRIMARY KEY,
	ToursID INT[],
	Login VARCHAR(30),
	Password VARCHAR(30),
	AccessLevel INT NULL
);

CREATE TABLE IF NOT EXISTS Transfer
(
	TransferID INT NOT NULL PRIMARY KEY,
	PlaneTicket INT NULL,
	TrainTicket INT NULL,
	BusTicket INT NULL
);

CREATE TABLE IF NOT EXISTS PlaneTicket
(
	PlaneTID INT NOT NULL PRIMARY KEY,
	Plane INT NULL,
	Seat INT NULL,
	Class INT NULL,
	CityFrom VARCHAR(30) NULL,
	CityTo VARCHAR(30) NULL,
	DepartureTime TIMESTAMP NULL,
	Luggage BOOL NULL,
	Cost INT NULL
);

CREATE TABLE IF NOT EXISTS TrainTicket
(
	TrainTID INT NOT NULL PRIMARY KEY,
	Train INT NULL,
	Coach INT NULL,
	Seat INT NULL,
	CityFrom VARCHAR(30) NULL,
	CityTo VARCHAR(30) NULL,
	DepartureTime TIMESTAMP NULL,
	ArrivalTime TIMESTAMP NULL,
	Linens BOOL NULL,
	Cost INT NULL
);

CREATE TABLE IF NOT EXISTS BusTicket
(
	BusTID INT NOT NULL PRIMARY KEY,
	Bus INT NULL,
	Seat INT NULL,
	CityFrom VARCHAR(30) NULL,
	CityTo VARCHAR(30) NULL,
	DepartureTime TIMESTAMP NULL,
	ArrivalTime TIMESTAMP NULL,
	Luggage BOOL NULL,
	Cost INT NULL
);